/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DIAMOND1HARDHAT } from "./DIAMOND1HARDHAT";
export * as factories from "./factories";
export { DIAMOND1HARDHAT__factory } from "./factories/DIAMOND1HARDHAT__factory";
