import "./globals.css";
import Navbar from "./components/navbar";
import WagmiProvider from "../context/wagmiProvider";
import { Poppins } from "next/font/google";
import Footer from "./components/footer";

const poppins = Poppins({
  weight: "400",
  variable: "--font-poppins",
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Scroll Kingdoms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body>
        <WagmiProvider>
          <Navbar />
          {children}
          <Footer />
        </WagmiProvider>
      </body>
    </html>
  );
}
